import React from "react";
import Head from "next/head";

interface Props {}

const Header: React.FC<Props> = () => {
  return (
    <Head>
      <title>Frontend Mentor | Todo app</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/images/favicon-32x32.png" />
    </Head>
  )
}

export default Header